services:
  nodeapp:
    build: .
    ports:
      - '3000:3000'
      - '3001:3001'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - tiff_inputs:/app/Server/temp_inputs
      - tiff_outputs:/app/Server/outputs
    depends_on:
      - geoserver
      - postgres
    networks:
      - mynetwork

  geoserver:
    image: docker.osgeo.org/geoserver:2.26.x
    ports:
      - '8080:8080'
    networks:
      - mynetwork
    environment:
      - CORS_ENABLED=true
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

  postgres:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123321'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: 'bridge'

volumes:
  geoserver_data:
  tiff_inputs:
  tiff_outputs:
  postgres_data:
